{% set version = "4.5.0" %}

package:
  name: tinydb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tinydb/tinydb-{{ version }}.tar.gz
  sha256: d287cd092f19a2b8553d0a6018f172c351268fb8619898eb87633d9e2c036344

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - poetry
    - pip
    - python
    - pytest-runner
    - conda-verify
  run:
    - python

test:
  imports:
    - tinydb

about:
  home: https://github.com/msiemens/tinydb
  license: MIT
  license_file: LICENSE
  license_family: MIT
  # license file is not included. Should raise this on upstream.
  #license_file: LICENCE
  summary: TinyDB is a tiny, document oriented database optimized for your happiness :)
  description: |
    TinyDB is a lightweight document oriented database optimized for your
    happiness :) It's written in pure Python and has no external
    dependencies. The target are small apps that would be blown away by a
    SQL-DB or an external database server.

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - msiemens
    - tacaswell
    - ericmjl
